//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int IdPerson { get; set; }
        public string firstName { get; set; }
        public string surName { get; set; }
        public string middleName { get; set; }
        public Position Position { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    }
}
